version: "{build}"

clone_depth: 1

environment:
  DOCKER_VERSION: 18.09.0
  GOPATH: c:\gopath

install:
  - mkdir %GOPATH%\src\github.com\docker
  - cd %GOPATH%\src\github.com\docker
  - git clone --depth 1 -b v%DOCKER_VERSION% https://github.com/docker/cli.git
  - set PATH=c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%;
  - go version
  - go env

before_build:
  - cd cli
  - ps: $env:VERSION = "$env:DOCKER_VERSION-ce"
  - ps: $env:GITCOMMIT = git rev-parse --short HEAD
  - ps: $env:GITCOMMIT_FULL = git rev-parse HEAD
  - ps: $env:BUILDTIME = Get-Date -Format o

build_script:
  - cd cmd\docker
  - >
    go build -v -tags "autogen"
    -ldflags "-linkmode=internal
    -X github.com/docker/cli/cli.Version=%VERSION%
    -X github.com/docker/cli/cli.GitCommit=%GITCOMMIT%
    -X github.com/docker/cli/cli.BuildTime=%BUILDTIME%"
    -o c:\projects\docker-cli-binary\docker.exe

after_build:
  - c:\projects\docker-cli-binary\docker.exe --version
  - 7z a c:\projects\docker-cli-binary\docker.exe.7z c:\projects\docker-cli-binary\docker.exe
  - ps: $env:ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 c:\projects\docker-cli-binary\docker.exe.7z).Hash

artifacts:
  - path: docker.exe.7z
    name: Docker CLI

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: |
      Docker CLI binary for Windows 64-bit.

      Built at commit `$(GITCOMMIT_FULL)` of https://github.com/docker/cli.

      | File          | SHA-256 sum |
      | ---           | ---         |
      | docker.exe.7z | `$(ARTIFACT_HASH)` |
    auth_token:
      secure: Jfjhx7TC03brqWcw+uUMXHJxj445SVeEcmSnDUV10ggRuU6UlzQMLSVGIBRqWD8v
    artifact: docker.exe.7z
    on:
      branch: master
      appveyor_repo_tag: true
