version: "{build}"

clone_depth: 1

cache:
  - '%LocalAppData%\go-build'

environment:
  DOCKER_VERSION: 19.03.13
  GOPATH: c:\gopath

install:
  - mkdir %GOPATH%\src\github.com\docker
  - cd %GOPATH%\src\github.com\docker
  - git clone --depth 1 -b v%DOCKER_VERSION% https://github.com/docker/cli.git
  - set PATH=c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%;
  - go version
  - go env

before_build:
  - cd cli
  - ps: $env:VERSION = "$env:DOCKER_VERSION-ce"
  - ps: $env:GITCOMMIT = git rev-parse --short HEAD
  - ps: $env:GITCOMMIT_FULL = git rev-parse HEAD
  - ps: $env:BUILDTIME = Get-Date -Format o

build_script:
  - cd cmd\docker
  - >
    go build -v -tags "autogen"
    -ldflags "-linkmode=internal
    -X github.com/docker/cli/cli/version.Version=%VERSION%
    -X github.com/docker/cli/cli/version.GitCommit=%GITCOMMIT%
    -X github.com/docker/cli/cli/version.BuildTime=%BUILDTIME%"
    -o %APPVEYOR_BUILD_FOLDER%\docker.exe

after_build:
  - "%APPVEYOR_BUILD_FOLDER%\\docker.exe --version"
  - 7z a %APPVEYOR_BUILD_FOLDER%\docker-v%DOCKER_VERSION%.7z %APPVEYOR_BUILD_FOLDER%\docker.exe
  - ps: |
      $env:ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 $env:APPVEYOR_BUILD_FOLDER\docker-v$env:DOCKER_VERSION.7z).Hash
      "$env:ARTIFACT_HASH  docker-v$env:DOCKER_VERSION.7z"| Out-File -Encoding ascii -File $env:APPVEYOR_BUILD_FOLDER\sha256sum.txt

artifacts:
  - path: docker-v$(DOCKER_VERSION).7z
    name: Docker CLI archive
  - path: sha256sum.txt
    name: SHA256 hash of Docker CLI archive

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: |
      Docker CLI binary for Windows 64-bit.

      Built https://github.com/docker/cli at commit `$(GITCOMMIT_FULL)`.

      | File                         | SHA-256 sum |
      | ---                          | ---         |
      | docker-v$(DOCKER_VERSION).7z | `$(ARTIFACT_HASH)` |
    auth_token:
      secure: Jfjhx7TC03brqWcw+uUMXHJxj445SVeEcmSnDUV10ggRuU6UlzQMLSVGIBRqWD8v
    artifact: docker-v$(DOCKER_VERSION).7z,sha256sum.txt
    on:
      branch: master
      appveyor_repo_tag: true
